// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfomjkMXovdDKg_nyZum7hyYzl-J9zfNU',
    appId: '1:648951226490:web:1c0e0caf9c9ee11c1d9bc3',
    messagingSenderId: '648951226490',
    projectId: 'flutter-sns-19038',
    authDomain: 'flutter-sns-19038.firebaseapp.com',
    storageBucket: 'flutter-sns-19038.appspot.com',
    measurementId: 'G-0EPR6Q40GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2MzVGufZmwWBKkuJ_8dcP_74mqJrO_3g',
    appId: '1:648951226490:android:92ff0b92c61c77f91d9bc3',
    messagingSenderId: '648951226490',
    projectId: 'flutter-sns-19038',
    storageBucket: 'flutter-sns-19038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtg7DQ6E5z_MGlYz5_ePGVxmx6tFNks4A',
    appId: '1:648951226490:ios:15802ae513db45b91d9bc3',
    messagingSenderId: '648951226490',
    projectId: 'flutter-sns-19038',
    storageBucket: 'flutter-sns-19038.appspot.com',
    iosBundleId: 'com.example.flutterSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtg7DQ6E5z_MGlYz5_ePGVxmx6tFNks4A',
    appId: '1:648951226490:ios:9f0904fccaf6b9021d9bc3',
    messagingSenderId: '648951226490',
    projectId: 'flutter-sns-19038',
    storageBucket: 'flutter-sns-19038.appspot.com',
    iosBundleId: 'com.example.flutterSns.RunnerTests',
  );
}
